### ISSUE TITLE
Static version

### ISSUE THREAD

**Issue by CC007** [delight-im/PHP-Str#1]
Hey I was wondering if you could provide static functions that take the string as an input, so that you don't have to use Str objects everywhere. These static functions would probably require the user to set the charset in a way, so you could make it so that the charset is an optional parameter and/or that you can specify the charset in a static setter.

**Comment by ocram** [comment]
Thanks for your feedback!

First, the charset has always been an optional parameter, see: https://github.com/delight-im/PHP-Str/blob/acc909edba3fb7290447ef62c1b1671f261e6664/src/Str.php#L28

If you just want a static interface because it better suits your needs or your preferences, it's already there, and you can use it today: https://github.com/delight-im/PHP-Str/blob/acc909edba3fb7290447ef62c1b1671f261e6664/src/Str.php#L40

If you want a completely static implementation for performance reasons, however, I'd suggest you should actually measure what impact the construction of those objects has in practice. I don't think it's significant.

Anyway, a static implementation instead of the current object-based implementation probably won't make it into this library. Sorry!

**Comment by CC007** [comment]
Actually the reason was not performance but coding preferences. My preference would be to use the methods directly, so that the programmer does not have to keep track of what kind of string you are operating on. Your implementation requires you to get a Str object before you can perform those operations like `startsWith()`. 

I do see why you did this though, but I'd like this implementation to be more transparent to the user.

The suggested static methods can of course use the current implementation under the hood and there is no problem if people want to also keep using the current implementation.

What I mean for example is:
```
public static function startsWith(string $str, string $prefix): string
{
    return s($str)->startsWith($prefix);
}
```
if you provide methods like these, the it would provide a lot more flexibility in coding styles and preferences.

**Comment by CC007** [comment]
PS: I used php7 typehints here for clarity but if you want backwards compatibility with php5.x these are of course not needed. In that case you could type cast the output.

**Comment by CC007** [comment]
PS2: and of course you could add the charset as an optional parameter. I understood that the charset is not needed in your code, but what I meant was to not reduce functionality for the static version of the implementation.

**Comment by ocram** [comment]
Ah, I see. Thanks!

I thought that instead of

```php
s($str)->startsWith($prefix);
// or
// (new Str($str))->startsWith($prefix);
```

you wanted something like

```php
Str::from($str)->startsWith($prefix);
```

which we already have, but you actually wanted

```php
Str::startsWith($str, $prefix);
```

which we don't have. Well, one could certainly do that, but I'm not sure it has a place in this repository.

For this repository, we have chosen the object-based solution for a number of reasons. First, that string which you want to operate on actually *is* an object, conceptually, so it makes sense to model it as an object in your code as well. Second, the current interface makes it even more obvious what the correct order is. If you read

```php
Str::contains($a, $b);
```

you wouldn't know right from the start if this looks for `$a` in `$b` or the other way round. The correct order is just a convention that you have to know. With the object-based approach, on the other hand, somebody else may come in, see your code, and know exactly what that code conveys. Third, with the `s(...)` shorthand function, the typing overhead is really negligible.

Anyway, if you really prefer that static interface, you could certainly create one yourself without having to touch this library's code. You would have full compatibility and just need to create the static wrapper for every single method that can be called on the objects.

**Comment by CC007** [comment]
Oh I completely agree with this. Using objects and their methods would indeed make more sense in an object oriented setting. The thing is that preferrably you would want it to be a functionality that was acting on the string objects themselves, rather than an intermediate object. Transparancy, encaptulation and all that. In the language Scala you can achieve this with mixins and in Go you are able to do it without anything but just a method declaration. I don't know for sure, but I don't think that php has constructs like that yet. That is why either your or my solutions are, from different perspectives, the best way to cope with what php has to offer. Optimally, I'd just want to be able to do something like:
```
$str = 'foobar';
$bool = $str->startsWith('foo');
...
```
Butadding this to php would require a whole lot of thinking about when mixins are allowed, how not to unintentionally leak data from classes and a whole lot of other headaches, so I see why this isn't available yet.

**Comment by CC007** [comment]
By the way, what you describe with `contains` can be very much improved with good parameter names. I never had any trouble with the php language functions like `array_merge` or `array_map`, because of their descriptive parameter names (and good documentation).

**Comment by ocram** [comment]
Of course, something like the example you showed, with object methods on the native PHP strings, would be the optimal solution. But that will only ever be possible if either PHP implements this in the core or if you add a native extension to PHP which does this. From pure PHP library code, as in this library, this cannot be implemented.

Now that we don't have this in PHP, we have to decide for an alternative solution, which is either the object-based solution implemented in this library or the static interface you suggested. For this library, we'll stick with the former.

Regarding your comment that a descriptive interface (as in this library) is not required if you have good parameter names, and that you never had problems with those array and string functions in PHP's core, let me tell you: Lots of people have had problems with those! And I was not talking about the situation when you *write* your code, where your IDE might assist you with information like

```
Str::contains(string $haystack, string $needle);
```

but about the situation when you're *reading* code, potentially from another author, and possibly even with you as a reader not being familiar with PHP. In that situation, all you'll see is what I showed above, namely

```
Str::contains($a, $b);
```

which does not tell you a lot about which parameter is what. Yes, one click and a shortcut for your IDE might bring up some assistance again, but that's one extra step which you don't want to do all the time while reading.
